'''

The sequence of triangle numbers is generated by adding the natural numbers.
What is the value of the first triangle number to have over five hundred divisors?

'''

i = 1
while 1:
    count = 1
    n = i * (i + 1) / 2
    for x in range(1, int(n**0.5)+1):
        if n % x == 0:
            count += 2
    print count        
    if count > 500:
        break
    i += 1
print "The smallest such number is:", n


# i=1

# while loopt:
# 	print i
# 	number = triange_num(i)
# 	loopt = divisors(number)

# 	i = i+1



